name: Dev PR Cleanup
on:
  pull_request:
    types: [closed]

jobs:
  Cleanup-DEV-PR:
    runs-on: ubuntu-latest

    env:
      REGISTRY: us-docker.pkg.dev
      GKE_CLUSTER: prvt-d-orbit-us-east1
      GKE_ZONE: us-east1
      PROJECT_ID: prj-83923-d-orbit-8092
      BASTION_PREFIX: d-orbit-us-east1-bastion
      PR_NUMBER: ${{github.event.number}}
      MAX_RETRIES: 3
      MAX_RETRY_DELAY: 10 # seconds

    steps:

      - name: Check PR_NUMBER is set
        run: |-
          if [ -z "$PR_NUMBER" ]; then
            echo "PR_NUMBER is not set"
            exit 1
          fi

      - name: Find available bastion host from pool
        run: |-
         echo "expect this is pass"

      - name: Retrieve cluster config
        run: |-
          echo "expecting this to just work"

      - name: Delete GKE resources from dev-pr namespace
        if: ${{ github.base_ref == 'main' }}
        run: |-
          echo "This is main branch, so running from dev-pr from main"

      - name: Delete GKE resources from adev-pr namespace
        if: ${{ github.base_ref == 'sada-george-develop' }}
        run: |-
          echo "This is develop branch, so running at adev-pr namespace  from sada-george-develop"

